backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: 'Pages'
    name: 'pages'
    # create: true
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Banner', name: 'banner', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Dicas'
        name: 'Dicas'
        file: 'content/dicas.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Imagem da página', name: 'thumbnail', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Post'
            name: 'post'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Imagem', name: 'thumbnail', widget: 'image' }
              - { label: 'Imagem Banner', name: 'banner', widget: 'image' }
              - {
                  label: 'Categoria',
                  name: 'Categoria',
                  widget: 'select',
                  options: ['home', 'dicas', 'nacional', 'internacional'],
                }
